/**
 * CSS Bundler for MadeInMaghribal
 * Concatenates modular CSS files from browser/styles/ into public/style.css.
 */
const fs = require('fs');
const path = require('path');

const projectRoot = path.join(__dirname, '..');
const stylesDir = path.join(projectRoot, 'browser/styles');
const outputFile = path.join(projectRoot, 'public/style.css');

const FILES_ORDER = [
  '00_theme.css',
  '01_base.css',
  '02_shared.css',
  '10_title.css',
  '20_heroine.css',
  '30_vn.css',
  '40_quiz.css',
  '50_result_ending.css',
  '51_turn_result.css',
  '90_debug.css'
];

function buildStyle() {
  console.log('Building CSS bundle...');
  let combinedCss = `/* \n * MadeInMaghribal - Combined Production Styles\n * Generated by tools/build-style.cjs\n * Do not edit public/style.css directly.\n */\n\n`;

  for (const filename of FILES_ORDER) {
    const fullPath = path.join(stylesDir, filename);
    if (fs.existsSync(fullPath)) {
      console.log(`Adding ${filename}...`);
      const content = fs.readFileSync(fullPath, 'utf8');
      combinedCss += `/* --- START: ${filename} --- */\n`;
      combinedCss += content;
      combinedCss += `\n/* --- END: ${filename} --- */\n\n`;
    } else {
      console.warn(`Warning: ${filename} not found.`);
    }
  }

  fs.writeFileSync(outputFile, combinedCss);
  console.log('CSS bundle created successfully at ' + outputFile);
}

if (require.main === module) {
  buildStyle();
}

module.exports = { buildStyle };
